export const CHANGE_SCSEARCHFORM = "CHANGE_SCSEARCHFORM";
export const CLEAR_SCSEARCHFORM = "CLEAR_SCSEARCHFORM";

export const CHANGE_USERSEARCHFORM = "CHANGE_USERSEARCHFORM";
export const CLEAR_USERSEARCHFORM = "CLEAR_USERSEARCHFORM";