export const SHOW_SCCREATE_MODAL = "SHOW_SCCREATE_MODAL";
export const HIDE_SCCREATE_MODAL = "HIDE_SCCREATE_MODAL";

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const STORE_ACCOUNT = 'STORE_ACCOUNT';
export const STORE_ACCOUNT_ERROR = "STORE_ACCOUNT_ERROR";
export const SIGNED_OUT = 'SIGNED_OUT'

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SERCH_USER_SUCCESS";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";


export const CONNECT_FAIL = "CONNECT_FAIL";


export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';


export const SEARCH_SC = "SEARCH_SC";
export const SEARCH_SC_SUCCESS = "SEARCH_SC_SUCCESS";
export const GET_SC_DETAIL = "GET_SC_DETAIL";
export const GET_SC_DETAIL_SUCCESS = "GET_SC_DETAIL_SUCCESS";
export const CREATE_NEW_SC = "CREATE_NEW_SC";