export const SHOW_IMAGE_SLIDER_DETAIL_MODAL = "SHOW_IMAGE_SLIDER_DETAIL_MODAL";
export const HIDE_IMAGE_SLIDER_DETAIL_MODAL = "HIDE_IMAGE_SLIDER_DETAIL_MODAL";

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_CONFIRM_DIALOG = "SHOW_CONFIRM_DIALOG";
export const HIDE_CONFIRM_DIALOG = "HIDE_CONFIRM_DIALOG";

export const FETCH_AMOUNT_BOOKING = "FETCH_AMOUNT_BOOKING";
export const HUB_CONNECTION = "HUB_CONNECTION";

export const STORE_ACCOUNT = 'STORE_ACCOUNT';
export const STORE_ACCOUNT_ERROR = "STORE_ACCOUNT_ERROR";
export const SIGNED_OUT = 'SIGNED_OUT'

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SERCH_USER_SUCCESS";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const CHANGE_ACCOUNT_STATUS = "CHANGE_ACCOUNT_STATUS";


export const CONNECT_FAIL = "CONNECT_FAIL";


export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';


export const SEARCH_SC = "SEARCH_SC";
export const SEARCH_SC_SUCCESS = "SEARCH_SC_SUCCESS";
export const GET_SC_DETAIL = "GET_SC_DETAIL";
export const GET_SC_DETAIL_SUCCESS = "GET_SC_DETAIL_SUCCESS";


export const FETCH_ALL_TRASACTION = "FETCH_ALL_TRASACTION";
export const SEARCH_DC_TRANSACTION = "SEARCH_DC_TRANSACTION";
export const SEARCH_DC_TRANSACTION_SUCCESS = "SEARCH_DC_TRANSACTION_SUCCESS";
export const SEARCH_CS_TRANSACTION = "SEARCH_CS_TRANSACTION";
export const SEARCH_CS_TRANSACTION_SUCCESS = "SEARCH_CS_TRANSACTION_SUCCESS";
export const GET_DC_TRANSACTION_DETAIL = "GET_DC_TRANSACTION_DETAIL";
export const GET_DC_TRANSACTION_DETAIL_SUCCESS = "GET_DC_TRANSACTION_DETAIL_SUCCESS";
export const GET_CS_TRANSACTION_DETAIL = "GET_CS_TRANSACTION_DETAIL";
export const GET_CS_TRANSACTION_DETAIL_SUCCESS = "GET_CS_TRANSACTION_DETAIL_SUCCESS";


export const SEARCH_BOOKING = "SEARCH_BOOKING";
export const SEARCH_BOOKING_SUCCESS = "SEARCH_BOOKING_SUCCESS";
export const GET_BOOKING_DETAIL = "GET_BOOKING_DETAIL";
export const GET_BOOKING_DETAIL_SUCCESS = "GET_BOOKING_DETAIL_SUCCESS";

export const FEATCH_IMAGESLIDER_IMAGES_USING = "FEATCH_IMAGESLIDER_IMAGES_USING";
export const FEATCH_IMAGESLIDER_IMAGES_USING_SUCCESS = "FEATCH_IMAGESLIDER_IMAGES_USING_SUCCESS";
export const FEATCH_IMAGESLIDER = "FEATCH_IMAGESLIDER";
export const FEATCH_IMAGESLIDER_SUCCESS = "FEATCH_IMAGESLIDER_SUCCESS";
export const CREATE_IMAGESLIDER_IMAGE = "CREATE_IMAGESLIDER_IMAGE";
export const CHANGE_ISSELECTED_IMAGESLIDER = "CHANGE_ISSELECTED_IMAGESLIDER";
export const VIEW_IMAGESLIDER_DETAIL = "VIEW_IMAGESLIDER_DETAIL";
export const SAVE_IMAGESLIDER = "SAVE_IMAGESLIDER";

export const FEATCH_ALL_REQUEST_REGISTER = "FEATCH_ALL_REQUEST_REGISTER";
export const SEARCH_COLLECTOR_REQUEST_REGISTER = "SEARCH_COLLECTOR_REQUEST_REGISTER";
export const SEARCH_COLLECTOR_REQUEST_REGISTER_SUCCESS = "SEARCH_COLLECTOR_REQUEST_REGISTER_SUCCESS";
export const SEARCH_DEALER_REQUEST_REGISTER = "SEARCH_DEALER_REQUEST_REGISTER";
export const SEARCH_DEALER_REQUEST_REGISTER_SUCCESS = "SEARCH_DEALER_REQUEST_REGISTER_SUCCESS";
export const GET_COLLECTOR_REQUEST_REGISTER = "GET_COLLECTOR_REQUEST_REGISTER";
export const GET_COLLECTOR_REQUEST_REGISTER_SUCCESS = "GET_COLLECTOR_REQUEST_REGISTER_SUCCESS";
export const GET_DEALER_REQUEST_REGISTER = "GET_DEALER_REQUEST_REGISTER";
export const GET_DEALER_REQUEST_REGISTER_SUCCESS = "GET_DEALER_REQUEST_REGISTER_SUCCESS";
export const CHANGE_REQUEST_REGISTER_STATUS = "CHANGE_REQUEST_REGISTER_STATUS";
export const UPDATE_COLLECTOR_REGISTER = "UPDATE_COLLECTOR_REGISTER";

export const SEARCH_DEALER = "SEARCH_DEALER";
export const SEARCH_DEALER_SUCCESS = "SEARCH_DEALER_SUCCESS";
export const GET_DEALER_DETAIL = "GET_DEALER_DETAIL";
export const GET_DEALER_DETAIL_SUCCESS = "GET_DEALER_DETAIL_SUCCESS";

export const GET_SYS_CONFIG_INFO = "GET_SYS_CONFIG_INFO";
export const GET_SYS_CONFIG_INFO_SUCCESS = "GET_SYS_CONFIG_INFO_SUCCESS";
export const MODIFY_SYS_CONFIG = "MODIFY_SYS_CONFIG";
export const CHANGE_CONFIG_INFO = "CHANGE_CONFIG_INFO";


export const GET_TRANSACTION_SERVICE = "GET_TRANSACTION_SERVICE";

export const GET_SELL_COLLECT_TRANS_FEE = "GET_SELL_COLLECT_TRANS_FEE";
export const GET_SELL_COLLECT_TRANS_FEE_SUCCESS = "GET_SELL_COLLECT_TRANS_FEE_SUCCESS";
export const MODIFY_SELL_COLLECT_TRANS_FEE = "MODIFY_SELL_COLLECT_TRANS_FEE";

export const GET_COLLECT_DEAL_TRANS_FEE = "GET_COLLECT_DEAL_TRANS_FEE";
export const GET_COLLECT_DEAL_TRANS_FEE_SUCCESS = "GET_COLLECT_DEAL_TRANS_FEE_SUCCESS";
export const MODIFY_COLLECT_DEAL_TRANS_FEE = "MODIFY_COLLECT_DEAL_TRANS_FEE";

export const GET_SELLER_AWARD_POINT = "GET_SELLER_AWARD_POINT";
export const GET_SELLER_AWARD_POINT_SUCCESS = "GET_SELLER_AWARD_POINT_SUCCESS";
export const MODIFY_SELLER_AWARD_POINT = "MODIFY_SELLER_AWARD_POINT";

export const GET_COLLECTOR_AWARD_POINT = "GET_COLLECTOR_AWARD_POINT";
export const GET_COLLECTOR_AWARD_POINT_SUCCESS = "GET_COLLECTOR_AWARD_POINT_SUCESS";
export const MODIFY_COLLECTOR_AWARD_POINT = "MODIFY_COLLECTOR_AWARD_POINT";


export const GET_CANCEL_REASON = "GET_CANCEL_REASON";
export const GET_CANCEL_REASON_SUCCESS = "GET_CANCEL_REASON_SUCCESS";
export const CREATE_NEW_CANCEL_REASON = "CREATE_NEW_CANCEL_REASON";
export const UPDATE_CANCEL_REASON = "UPDATE_CANCEL_REASON";
export const DELETE_CANCEL_REASON = "DELETE_CANCEL_REASON";


export const SEARCH_SELLER_COMPLAINT = "SEARCH_SELLER_COMPLAINT";
export const GET_SELLER_COMPLAINT = "GET_SELLER_COMPLAINT";

export const SEARCH_COLLECTOR_COMPLAINT = "SEARCH_COLLECTOR_COMPLAINT";
export const GET_COLLECTOR_COMPLAINT = "GET_COLLECTOR_COMPLAINT";

export const SEARCH_DEALER_COMPLAINT = "SEARCH_DEALER_COMPLAINT";
export const GET_DEALER_COMPLAINT = "GET_DEALER_COMPLAINT";

export const REPLY_SELLER_COMPLAINT = "REPLY_SELLER_COMPLAINT";
export const REPLY_COLLECTOR_COMPLAINT = "REPLY_COLLECTOR_COMPLAINT";
export const REPLY_DEALER_COMPLAINT = "REPLY_DEALER_COMPLAINT";


export const REGISTER_COLLECTOR_ACCOUNT = "REGISTER_COLLECTOR_ACCOUNT";
export const REQUEST_COLLECTOR_REGISTER_OTP = "REQUEST_COLLECTOR_REGISTER_OTP";
export const CONFIRM_COLLECTOR_REGISTER_OTP = "CONFIRM_COLLECTOR_REGISTER_OTP";
export const SAVE_COLLECTOR_REGISTER_OTP = "SAVE_COLLECTOR_REGISTER_OTP";
export const CLEAR_COLLECTOR_REGISTER_OTP = "CLEAR_COLLECTOR_REGISTER_OTP";


export const GET_STATISTIC_DASHBOARD = "GET_STATISTIC_DASHBOARD";
export const FEATCH_STATISTIC_DASHBOARD = "FEATCH_STATISTIC_DASHBOARD";