export const CHANGE_SCSEARCHFORM = "CHANGE_SCSEARCHFORM";
export const CLEAR_SCSEARCHFORM = "CLEAR_SCSEARCHFORM";

export const CHANGE_USERSEARCHFORM = "CHANGE_USERSEARCHFORM";
export const CLEAR_USERSEARCHFORM = "CLEAR_USERSEARCHFORM";

export const CHANGE_DC_TRANSACTION_SEARCHFORM = "CHANGE_DC_TRANSACTION_SEARCHFORM";
export const CLEAR_DC_TRANSACTION_SEARCHFORM = "CLEAR_DC_TRANSACTION_SEARCHFORM";

export const CHANGE_CS_TRANSACTION_SEARCHFORM = "CHANGE_CS_TRANSACTION_SEARCHFORM";
export const CLEAR_CS_TRANSACTION_SEARCHFORM = "CLEAR_CS_TRANSACTION_SEARCHFORM";


export const CHANGE_BOOKING_SEARCHFORM = "CHANGE_BOOKING_SEARCHFORM";
export const CLEAR_BOOKING_SEARCHFORM = "CLEAR_BOOKING_SEARCHFORM";

export const CHANGE_COLLECTOR_REQUEST_REGISTER_SEARCHFORM = "CHANGE_COLLECTOR_REQUEST_REGISTER_SEARCHFORM";
export const CLEAR_COLLECTOR_REQUEST_REGISTER_SEARCHFORM = "CLEAR_COLLECTOR_REQUEST_REGISTER_SEARCHFORM";

export const CHANGE_DEALER_REQUEST_REGISTER_SEARCHFORM = "CHANGE_DEALER_REQUEST_REGISTER_SEARCHFORM";
export const CLEAR_DEALER_REQUEST_REGISTER_SEARCHFORM = "CLEAR_COLLECTOR_REQUEST_REGISTER_SEARCHFORM";

export const CHANGE_DEALER_SEARCHFORM = "CHANGE_DEALER_SEARCHFORM";
export const CLEAR_DEALER_SEARCHFORM = "CLEAR_DEALER_SEARCHFORM";



export const CHANGE_SELLER_COMPLAINT_SEARCHFORM = "CHANGE_SELLER_COMPLAINT_SEARCHFORM";
export const CLEAR_SELLER_COMPLAINT_SEARCHFORM = "CLEAR_SELLER_COMPLAINT_SEARCHFORM";

export const CHANGE_COLLECTOR_COMPLAINT_SEARCHFORM = "CHANGE_COLLECTOR_COMPLAINT_SEARCHFORM";
export const CLEAR_COLLECTOR_COMPLAINT_SEARCHFORM = "CLEAR_COLLECTOR_COMPLAINT_SEARCHFORM";

export const CHANGE_DEALER_COMPLAINT_SEARCHFORM = "CHANGE_DEALER_COMPLAINT_SEARCHFORM";
export const CLEAR_DEALER_COMPLAINT_SEARCHFORM = "CLEAR_DEALER_COMPLAINT_SEARCHFORM";