export const SHOW_SCCREATE_MODAL = "SHOW_SCCREATE_MODAL";
export const HIDE_SCCREATE_MODAL = "HIDE_SCCREATE_MODAL";

export const SHOW_IMAGE_SLIDER_DETAIL_MODAL = "SHOW_IMAGE_SLIDER_DETAIL_MODAL";
export const HIDE_IMAGE_SLIDER_DETAIL_MODAL = "HIDE_IMAGE_SLIDER_DETAIL_MODAL";

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_CONFIRM_DIALOG = "SHOW_CONFIRM_DIALOG";
export const HIDE_CONFIRM_DIALOG = "HIDE_CONFIRM_DIALOG";

export const FETCH_UNIT = "FETCH_UNIT";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";
export const FETCH_AMOUNT_BOOKING = "FETCH_AMOUNT_BOOKING";
export const HUB_CONNECTION = "HUB_CONNECTION";

export const STORE_ACCOUNT = 'STORE_ACCOUNT';
export const STORE_ACCOUNT_ERROR = "STORE_ACCOUNT_ERROR";
export const SIGNED_OUT = 'SIGNED_OUT'

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SERCH_USER_SUCCESS";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";


export const CONNECT_FAIL = "CONNECT_FAIL";


export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';



export const SEARCH_SC = "SEARCH_SC";
export const SEARCH_SC_SUCCESS = "SEARCH_SC_SUCCESS";
export const UPDATE_SC = "UPDATE_SC"
export const GET_SC_DETAIL = "GET_SC_DETAIL";
export const GET_SC_DETAIL_SUCCESS = "GET_SC_DETAIL_SUCCESS";
export const CREATE_NEW_SC = "CREATE_NEW_SC";
export const REMOVE_SC = "REMOVE_SC";;


export const SEARCH_UNIT = "SEARCH_UNIT";
export const REMOVE_UNIT = "REMOVE_UNIT";
export const SEARCH_UNIT_SUCCESS = "SEARCH_UNIT_SUCCESS";
export const CREATE_NEW_UNIT = "CREATE_NEW_UNIT"

export const FETCH_ALL_TRASACTION = "FETCH_ALL_TRASACTION";
export const SEARCH_DC_TRANSACTION = "SEARCH_DC_TRANSACTION";
export const SEARCH_DC_TRANSACTION_SUCCESS = "SEARCH_DC_TRANSACTION_SUCCESS";
export const SEARCH_CS_TRANSACTION = "SEARCH_CS_TRANSACTION";
export const SEARCH_CS_TRANSACTION_SUCCESS = "SEARCH_CS_TRANSACTION_SUCCESS";
export const GET_DC_TRANSACTION_DETAIL = "GET_DC_TRANSACTION_DETAIL";
export const GET_DC_TRANSACTION_DETAIL_SUCCESS = "GET_DC_TRANSACTION_DETAIL_SUCCESS";
export const GET_CS_TRANSACTION_DETAIL = "GET_CS_TRANSACTION_DETAIL";
export const GET_CS_TRANSACTION_DETAIL_SUCCESS = "GET_CS_TRANSACTION_DETAIL_SUCCESS";


export const SEARCH_BOOKING = "SEARCH_BOOKING";
export const SEARCH_BOOKING_SUCCESS = "SEARCH_BOOKING_SUCCESS";
export const GET_BOOKING_DETAIL = "GET_BOOKING_DETAIL";
export const GET_BOOKING_DETAIL_SUCCESS = "GET_BOOKING_DETAIL_SUCCESS";


export const SEARCH_DC_FEEDBACK = "SEARCH_DC_FEEDBACK";
export const SEARCH_DC_FEEDBACK_SUCCESS = "SEARCH_DC_FEEDBACK_SUCCESS";
export const SEARCH_CS_FEEDBACK = "SEARCH_CS_FEEDBACK";
export const SEARCH_CS_FEEDBACK_SUCCESS = "SEARCH_CS_FEEDBACK_SUCCESS";


export const FEATCH_IMAGESLIDER_IMAGES_USING = "FEATCH_IMAGESLIDER_IMAGES_USING";
export const FEATCH_IMAGESLIDER_IMAGES_USING_SUCCESS = "FEATCH_IMAGESLIDER_IMAGES_USING_SUCCESS";
export const FEATCH_IMAGESLIDER = "FEATCH_IMAGESLIDER";
export const FEATCH_IMAGESLIDER_SUCCESS = "FEATCH_IMAGESLIDER_SUCCESS";
export const CREATE_IMAGESLIDER_IMAGE = "CREATE_IMAGESLIDER_IMAGE";
export const CHANGE_ISSELECTED_IMAGESLIDER = "CHANGE_ISSELECTED_IMAGESLIDER";
export const VIEW_IMAGESLIDER_DETAIL = "VIEW_IMAGESLIDER_DETAIL";
export const SAVE_IMAGESLIDER = "SAVE_IMAGESLIDER";

export const FEATCH_ALL_REQUEST_REGISTER = "FEATCH_ALL_REQUEST_REGISTER";
export const SEARCH_COLLECTOR_REQUEST_REGISTER = "SEARCH_COLLECTOR_REQUEST_REGISTER";
export const SEARCH_COLLECTOR_REQUEST_REGISTER_SUCCESS = "SEARCH_COLLECTOR_REQUEST_REGISTER_SUCCESS";
export const SEARCH_DEALER_REQUEST_REGISTER = "SEARCH_DEALER_REQUEST_REGISTER";
export const SEARCH_DEALER_REQUEST_REGISTER_SUCCESS = "SEARCH_DEALER_REQUEST_REGISTER_SUCCESS";
export const GET_COLLECTOR_REQUEST_REGISTER = "GET_COLLECTOR_REQUEST_REGISTER";
export const GET_COLLECTOR_REQUEST_REGISTER_SUCCESS = "GET_COLLECTOR_REQUEST_REGISTER_SUCCESS";
export const GET_DEALER_REQUEST_REGISTER = "GET_DEALER_REQUEST_REGISTER";
export const GET_DEALER_REQUEST_REGISTER_SUCCESS = "GET_DEALER_REQUEST_REGISTER_SUCCESS";