export const CHANGE_SCSEARCHFORM = "CHANGE_SCSEARCHFORM";
export const CLEAR_SCSEARCHFORM = "CLEAR_SCSEARCHFORM";

export const CHANGE_USERSEARCHFORM = "CHANGE_USERSEARCHFORM";
export const CLEAR_USERSEARCHFORM = "CLEAR_USERSEARCHFORM";

export const CHANGE_UNITSEARCHFORM = "CHANGE_UNITSEARCHFORM";
export const CLEAR_UNITSEARCHFORM = "CLEAR_UNITSEARCHFORM";

export const CHANGE_DC_TRANSACTION_SEARCHFORM = "CHANGE_DC_TRANSACTION_SEARCHFORM";
export const CLEAR_DC_TRANSACTION_SEARCHFORM = "CLEAR_DC_TRANSACTION_SEARCHFORM";

export const CHANGE_CS_TRANSACTION_SEARCHFORM = "CHANGE_CS_TRANSACTION_SEARCHFORM";
export const CLEAR_CS_TRANSACTION_SEARCHFORM = "CLEAR_CS_TRANSACTION_SEARCHFORM";


export const CHANGE_BOOKING_SEARCHFORM = "CHANGE_BOOKING_SEARCHFORM";
export const CLEAR_BOOKING_SEARCHFORM = "CLEAR_BOOKING_SEARCHFORM";

export const CHANGE_DC_FEEDBACK_SEARCHFORM = "CHANGE_DC_FEEDBACK_SEARCHFORM";
export const CLEAR_DC_FEEDBACK_SEARCHFORM = "CLEAR_DC_FEEDBACK_SEARCHFORM";

export const CHANGE_CS_FEEDBACK_SEARCHFORM = "CHANGE_CS_FEEDBACK_SEARCHFORM";
export const CLEAR_CS_FEEDBACK_SEARCHFORM = "CLEAR_CS_FEEDBACK_SEARCHFORM";